version: "3"

services:
  flask_app:
    container_name: flask_app
    image: luxonis_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=Jan0247722623@
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
